# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImitateWeChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImitateWeChat
  pod 'Mantle'
  pod 'SnapKit'
  target 'ImitateWeChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImitateWeChatUITests' do
    # Pods for testing
  end

end
